name: Android APK Build From Zip

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract Project Zips
      run: |
        unzip -o StepTracker.zip
        unzip -o StepTrackerBroadcast.zip

    - name: Inject Web Client ID into strings.xml
      run: |
        find . -name "strings.xml" -path "*/src/main/res/values/*" -exec sed -i 's/SİZİN_WEB_CLIENT_ID/600624936310-vjh82pio4figis8al4k6j7gmp4klk964.apps.googleusercontent.com/g' {} +

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Precise Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.2'

    - name: Fix Firebase JSON Location
      run: |
        # google-services.json faylını tətbiqin app qovluğunun içinə kopyalayır
        cp google-services.json StepTracker/app/ || true
        cp google-services.json StepTrackerBroadcast/app/ || true

    - name: Build Main App with Global Gradle
      run: |
        BUILD_DIR=$(dirname $(find . -name "settings.gradle" | head -n 1))
        cd "$BUILD_DIR"
        gradle assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: StepTracker-Main-App
        path: |
          **/build/outputs/apk/debug/*.apk
          
